import uuid
from models import User, Messages, Sublease, Apartment, db
from faker import Faker
import random

fake = Faker()

usernames= ['adam','billy','GuestAccount','chase','david']

apartment_names =  ['The Outpost', 'The Thompson', 'Bobcat Village', 'College Town San Marcos', 'Vie Lofts at San Marcos', 'Dakota Ranch Student Apartments', 'The Grove at San marcos', 'Uptown Square', 'The Junction San Marcos', 'The View on the Square', 'Westfield Apartments', 'The Village on Telluride', 'The Cottages at San Marcos' 'The Lodge Apartments', 'Arba', 'Bishops Square', 'The Avenue at San Marcos', 'Copper Beech at San Marcos', 'Cheatham Street Flats', 'redpoint San Marcos', 'Sanctuary Lofts', 'Millenium on Post', 'The Retreat', 'Elevation on Post', 'The Lyndon at Springtown', 'The Social SMTX', 'The Local Downtown', 'Vistas San Marcos', 'The Oasis San Marcos', 'Highcrest Apartments', 'The Timbers', 'Hill Country Apartments', 'Vintage Pads Apartments', 'Leah Avenue Townhomes', 'CastleRock at San Marcos', 'Villagio Apartments', 'The Fitzroy San Marcos', 'The Edge', 'Pointe San Marcos', 'Riverside Ranch', 'The Parlor', 'River Oaks Villas Apartments', 'Sadler House Apartments', 'Hawthorne at Blanco Riverwalk', 'Springmarc', 'Savannah Club Apartments', 'Sutton Apartments', 'Mosscliff Apartments', 'Encino Pointe']

sublease_desc = ["Spacious apartment near downtown attractions",
    "Cozy studio in trendy neighborhood available",
    "Fully furnished one-bedroom with utilities included",
    "Charming two-bedroom in quiet community",
    "Luxury high-rise with stunning city views",
    "Bright and modern loft in desirable location",
    "Pet-friendly three-bedroom with outdoor space",
    "Renovated historic building with modern amenities",
    "Affordable shared apartment in convenient location",
    "Private room in quiet residential neighborhood",
    "Sunny and stylish apartment with balcony",
    "Newly renovated one-bedroom with parking included",
    "Elegant two-bedroom with open floor plan",
    "Spacious townhome with attached garage",
    "Beautifully furnished apartment with pool access",
    "Modern and sleek studio in prime location",
    "Renovated duplex with private backyard oasis",
    "Quiet and cozy apartment with character",
    "Pet-friendly apartment with on-site dog park",
    "Large and luxurious three-bedroom with views",
    "Stylish and modern apartment in hip neighborhood",
    "Sunny and spacious one-bedroom with amenities",
    "Charming apartment with hardwood floors throughout",
    "Fully furnished two-bedroom with outdoor space",
    "Bright and airy loft with city views",
    "Newly renovated townhome with garage parking",
    "Quaint one-bedroom with vintage charm",
    "Private bedroom in shared apartment community",
    "Luxurious penthouse with panoramic city views",
    "Spacious two-bedroom with balcony and fireplace",
    "Beautifully renovated historic building with modern finishes",
    "Pet-friendly apartment with private patio",
    "Large and airy one-bedroom with pool access",
    "Modern and stylish two-bedroom with amenities",
    "Renovated duplex with fenced backyard",
    "Sleek and spacious apartment with city views",
    "Newly renovated three-bedroom with garage parking",
    "Cozy and comfortable one-bedroom with character",
    "Private bedroom in modern shared apartment",
    "Luxury apartment with resort-style amenities",
    "Stylish two-bedroom with balcony and pool access",
    "Charming historic building with modern updates",
    "Pet-friendly apartment with on-site park",
    "Spacious and sunny studio with city views",
    "Updated one-bedroom with outdoor space",
    "Beautifully furnished apartment in prime location",
    "Renovated two-bedroom with hardwood floors",
    "Bright and spacious townhome with garage",
    "Modern and sleek studio with amenities",
    "Renovated three-bedroom with pool access",
    "Private bedroom in newly renovated apartment",
    "Luxury high-rise with top-notch amenities",
    "Stylish and spacious two-bedroom with fireplace",
    "Cozy one-bedroom in quiet community",
    "Pet-friendly apartment with fenced backyard",
    "Spacious and bright one-bedroom with pool",
    "Updated two-bedroom with outdoor space",
    "Furnished apartment with flexible lease options",
    "Renovated historic building with stylish finishes",
    "Sleek and modern apartment with amenities",
    "Luxury townhome with attached garage",
    "Spacious three-bedroom with private balcony",
    "Beautifully updated one-bedroom with city views",
    "Private room in shared apartment community",
    "Charming two-bedroom with historic details",
    "Pet-friendly apartment with outdoor play area",
    "Modern and stylish one-bedroom with amenities",
    "Spacious and updated townhome with garage",
    "Bright and airy studio with outdoor space",
    "Newly renovated three-bedroom with pool",
    "Private bedroom in fully furnished apartment",
    "Luxury high-rise with stunning amenities and breathtaking views",
"Stylish one-bedroom with balcony and pool access",
"Renovated duplex with modern finishes",
"Cozy and comfortable studio in quiet community",
"Pet-friendly apartment with on-site pet spa",
"Spacious and sunny two-bedroom with city views",
"Updated one-bedroom with hardwood floors",
"Beautifully furnished apartment with flexible lease terms",
"Modern and sleek two-bedroom with amenities",
"Renovated townhome with private patio",
"Bright and spacious three-bedroom with pool",
"Private bedroom in shared apartment with gym",
"Charming historic building with updated amenities",
"Pet-friendly apartment with private dog run",
"Spacious and updated two-bedroom with garage",
"Furnished studio in prime location",
"Renovated three-bedroom with private balcony",
"Luxury apartment with on-site fitness center",
"Stylish and modern one-bedroom with fireplace",
"Cozy and comfortable two-bedroom with character",
"Pet-friendly apartment with on-site grooming salon",
"Spacious and sunny three-bedroom with pool",
"Updated two-bedroom with balcony and pool access",
"Beautifully renovated townhome with hardwood floors",
"Private room in shared apartment with pool",
"Luxury high-rise with top-of-the-line amenities",
"Stylish studio in desirable location",
"Renovated historic building with stunning finishes",
"Cozy and comfortable three-bedroom with character",
"Pet-friendly apartment with outdoor recreation area",
"Spacious and updated one-bedroom with garage",
"Furnished two-bedroom with outdoor space",
"Modern and sleek three-bedroom with amenities",
"Renovated duplex with private balcony",
"Bright and spacious townhome with pool access",
"Private bedroom in shared apartment with rooftop deck",
"Charming one-bedroom with historic details",
"Pet-friendly apartment with on-site pet wash",
"Spacious and sunny studio with pool",
"Updated three-bedroom with balcony and fireplace",
"Beautifully furnished apartment in trendy neighborhood",
"Luxury townhome with private garage",
"Stylish and modern two-bedroom with pool access",
"Cozy and comfortable townhome in quiet community",
"Pet-friendly apartment with outdoor lounge area",
"Spacious and updated three-bedroom with garage",
"Furnished studio with flexible lease options",
"Renovated townhome with private backyard",
"Bright and airy one-bedroom with city views",
"Private room in shared apartment with laundry facilities",
"Luxury high-rise with top-notch views",
"Stylish one-bedroom with hardwood floors",
"Renovated historic building with modern upgrades",
"Cozy and comfortable four-bedroom with character",
"Pet-friendly apartment with on-site park and playground",
"Spacious and sunny two-bedroom with pool access",
"Updated one-bedroom with private balcony",
"Beautifully furnished apartment with all utilities included",
"Modern and sleek four-bedroom with amenities",
"Renovated duplex with private patio",
"Bright and spacious three-bedroom with city views",
"Private bedroom in shared apartment with study room",
"Charming two-bedroom with modern finishes",
"Pet-friendly apartment with indoor pet spa",
"Spacious and updated four-bedroom with garage",
"Furnished one-bedroom with outdoor balcony",
"Renovated townhome with pool access",
"Luxury apartment with stunning finishes",
"Stylish and modern three-bedroom with pool access",
"Cozy and comfortable townhome with private backyard",
"Pet-friendly apartment with on-site dog wash",
"Spacious and updated studio with garage"]
cities = ['san marcos', 'austin', 'houston', 'san antonio', 'dallas']


def addfakedata():
    for aptname in apartment_names:
        newApartment = Apartment(
            name = aptname,
            pets = fake.boolean(),
            pool = fake.boolean(),
            gym = fake.boolean(),
            incldUtilities = fake.boolean(),
            shuttleRte = fake.boolean(),
            indvLeasing = fake.boolean(),
            wsherDryer = fake.boolean(),
            furnished = fake.boolean(),
            rmMatching = fake.boolean(),
            rating = random.randint(0,5),
            phone = fake.phone_number(),
            link = fake.url(),
        )
        db.session.add(newApartment)

    db.session.commit()

def addfakesublets():
    for i in range(5):
        newSublet = Sublease(
            id = str(uuid.uuid4()),
            subleaser_id = random.choice(usernames),
            apartment_name = random.choice(apartment_names),
            rent = int(random.gauss(750,175)),
            bed = random.randint(1,6),
            bath = random.randint(1,6),
            sqft = random.gauss(1000,500),
            description = random.choice(sublease_desc),
            location = random.choice(cities),
            image_path = f'images/download ({random.randint(1,14)}).jpeg'
        )
        db.session.add(newSublet)

    db.session.commit()